Feature/#79 initialize discrete choice
bperry12/pymanda pull request #81
Opened 2020-09-09 20:33 UTC by suhail-thahir-sat3ba

closes #79

2020-09-09 21:03 UTC, bperry12 requested changes

2020-10-02 17:06 UTC, bperry12 requested changes

2020-10-02 17:06 UTC, bperry12 commented on pymanda/choices.py
> +        corp_var = True):
calling this "corp_var" is confusing. maybe call it "use_corp_var" instead? also, add it to the documentation.

2020-10-02 17:06 UTC, bperry12 commented on pymanda/choices.py
> +        y_hat['choice'] = cd.data[cd.choice_var]
i think this should be based on "choice" see lines 668-671 above

2020-10-02 17:06 UTC, bperry12 commented on pymanda/choices.py
> +    def diversion(self, cd, y_hat, choices):
we need to modify this to allow people to change between corp_var and choice_var for different diversion runs. it's okay to have a default built in as you do, but it needs to be modifiable so i can run diversions for a single hospital or for a hospital group without re-estimating the model.

2020-10-02 17:06 UTC, bperry12 commented on pymanda/choices.py
> +            df = df / df.sum()
what's going on here?

2020-10-02 18:39 UTC, suhail-thahir-sat3ba commented on pymanda/choices.py
> +        corp_var = True):
switched to "use_corp"

2020-10-02 18:42 UTC, suhail-thahir-sat3ba commented on pymanda/choices.py
> +            Returns ChoiceData observations with group and diversion probabilities.
Removed because fit returns nothing

2020-10-02 18:50 UTC, suhail-thahir-sat3ba commented on pymanda/choices.py
> +            for i in range(3, len(self.coef_order)+3):
Because the last 3 columns are choice, grouped, and group. For creating bins, we want to ignore these columns

2020-10-02 19:17 UTC, suhail-thahir-sat3ba commented on pymanda/choices.py
> +                X = pd.merge(X, screen, how='left', left_on=bin_by_cols,right_index=True)
I can't think of any way and after some research could not find any alternatives. Is the worry resource consumption? I believe left merges use less resources because it keeps the left frame inplace.

2020-10-02 19:25 UTC, suhail-thahir-sat3ba commented on pymanda/choices.py
> +                X['grouped'] = X['grouped'] | X['count']
Line 579 updates which rows to count as "grouped". So if a row was previously grouped or grouped in the current iteration, it will be changed to True

2020-10-02 20:03 UTC, suhail-thahir-sat3ba commented on pymanda/choices.py
> +            df = df / df.sum()
Line 701 sums up the observations diverted to each other hospital. Then line 702 converts to shares.

2020-10-02 20:26 UTC, bperry12 commented on pymanda/choices.py
> +                X = pd.merge(X, screen, how='left', left_on=bin_by_cols,right_index=True)
yeah, merges are expensive, but i think it's okay.

2020-10-02 20:52 UTC, bperry12 commented on pymanda/choices.py
> +    def diversion(self, cd, y_hat, choices):
```suggestion
    def diversion(self, cd, choice_probs, div_choices, div_choices_var):
```

2020-10-02 20:53 UTC, bperry12 commented on pymanda/choices.py
> +    def diversion(self, cd, y_hat, choices):
```suggestion
    if div_choices_var == None:
        div_choices_var = cd.corp_var
```

2020-10-07 14:01 UTC, bperry12 commented on pymanda/choices.py
> +        if self.solver == 'semiparametric':
is this done?

2020-10-07 14:03 UTC, bperry12 approved these changes

2020-10-07 14:04 UTC, suhail-thahir-sat3ba commented on pymanda/choices.py
> +        if self.solver == 'semiparametric':
yes, there is a function called self.check_is_fitted()

2020-10-07 14:06 UTC, merged